openapi: 3.2.0
info:
  title: PlanRadar's API Documentation Steps V2 API
  version: '2.0'
  description: Welcome to PlanRadar's API documentation, here you can find all the details about our APIs as well as test them online.
servers:
- url: /
tags:
- name: Steps V2
paths:
  /api/v2/{customer_id}/projects/{project_id}/approval_requests/{approval_request_id}/steps:
    post:
      summary: create new step for already completed approval requests
      tags:
      - Steps V2
      description: this is only for creating steps for completed approval requests
      security:
      - apiKey: []
      parameters:
      - name: customer_id
        in: path
        required: true
        schema:
          type: string
          default: '100000'
      - name: project_id
        in: path
        required: true
        schema:
          type: string
      - name: approval_request_id
        in: path
        required: true
        schema:
          type: string
      responses:
        '422':
          description: Requests Not Created
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                data:
                  type: object
                  properties:
                    attributes:
                      type: object
                      properties:
                        subject:
                          type: string
                        message:
                          type: string
                        description:
                          type: string
                        name:
                          type: string
                        steps:
                          type: array
                          items:
                            type: object
                            properties:
                              duration:
                                type: number
                                default: 1
                              approvers:
                                type: array
                                items:
                                  type: string
                                default:
                                - oll
                              name:
                                type: string
                                default: step_name
      operationId: postApiV2ByCustomerIdProjectsByProjectIdApprovalRequestsByApprovalRequestIdSteps
      x-operation-id-source: derived
  /api/v2/{customer_id}/approval_workflows/{approval_workflow_id}/steps/{step_id}/update_workflow_step:
    put:
      summary: update step in global workflow
      tags:
      - Steps V2
      description: this api only for updating workflow steps
      security:
      - apiKey: []
      parameters:
      - name: customer_id
        in: path
        required: true
        schema:
          type: string
          default: '100000'
      - name: approval_workflow_id
        in: path
        required: true
        schema:
          type: string
      - name: step_id
        in: path
        required: true
        schema:
          type: string
      responses:
        '404':
          description: step not found
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                data:
                  type: object
                  properties:
                    attributes:
                      type: object
                      properties:
                        name:
                          type: string
      operationId: putApiV2ByCustomerIdApprovalWorkflowsByApprovalWorkflowIdStepsByStepIdUpdateWorkflowStep
      x-operation-id-source: derived
components:
  securitySchemes:
    apiKey:
      type: apiKey
      name: X-PlanRadar-API-Key
      in: header
externalDocs:
  description: Find out more about our development portal
  url: https://www.planradar.com/knowledge-base-overview/
