openapi: 3.2.0
info:
  title: PlanRadar's API Documentation Invitations API
  version: '2.0'
  description: Welcome to PlanRadar's API documentation, here you can find all the details about our APIs as well as test them online.
servers:
- url: /
tags:
- name: Invitations
paths:
  /api/{customer_id}/invitations/{id}:
    delete:
      summary: Delete an invitation
      tags:
      - Invitations
      security:
      - apiKey: []
      parameters:
      - name: customer_id
        in: path
        required: true
        schema:
          type: string
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '404':
          description: Invitation Not Found
      operationId: deleteApiByCustomerIdInvitationsById
      x-operation-id-source: derived
  /api/{customer_id}/invitations/{id}/resend_invitation:
    put:
      summary: Resende invitation
      tags:
      - Invitations
      security:
      - apiKey: []
      parameters:
      - name: customer_id
        in: path
        required: true
        schema:
          type: string
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '404':
          description: Invitation Not Found
      operationId: putApiByCustomerIdInvitationsByIdResendInvitation
      x-operation-id-source: derived
  /api/{customer_id}/invitations/search:
    get:
      summary: Search for invitations
      tags:
      - Invitations
      parameters:
      - name: customer_id
        in: path
        required: true
        schema:
          type: string
      - name: order_by
        in: query
        schema:
          type: string
      - name: order_how
        in: query
        schema:
          type: string
      - name: page
        in: query
        schema:
          type: integer
      - name: pageSize
        in: query
        schema:
          type: integer
      - name: searchterm
        in: query
        schema:
          type: string
      responses:
        '404':
          description: Customer Not Found
      operationId: getApiByCustomerIdInvitationsSearch
      x-operation-id-source: derived
  /api/{customer_id}/invitations/accept:
    post:
      summary: Accept invitation
      tags:
      - Invitations
      security:
      - apiKey: []
      parameters:
      - name: customer_id
        in: path
        required: true
        schema:
          type: string
      - name: time_zone_name
        in: query
        schema:
          type: string
      responses:
        '404':
          description: Invitation Not Found
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                password:
                  type: string
                retype_password:
                  type: string
                terms:
                  type: boolean
                uuid:
                  type: string
              required:
              - password
              - retype_password
              - terms
      operationId: postApiByCustomerIdInvitationsAccept
      x-operation-id-source: derived
  /api/{customer_id}/invitations/count_pending_invitations:
    get:
      summary: Retrieve number of pending invitations
      tags:
      - Invitations
      parameters:
      - name: customer_id
        in: path
        required: true
        schema:
          type: string
      - name: last_sync_date
        in: query
        schema:
          type: string
      - name: sort
        in: query
        schema:
          type: string
      - name: pagesize
        in: query
        schema:
          type: string
      - name: page
        in: query
        schema:
          type: string
      - name: search
        in: query
        schema:
          type: string
      responses:
        '404':
          description: Customer Not Found
      operationId: getApiByCustomerIdInvitationsCountPendingInvitations
      x-operation-id-source: derived
  /api/:customer_id/invitations:
    post:
      summary: Create new invitation
      tags:
      - Invitations
      security:
      - apiKey: []
      parameters:
      - name: customer_id
        in: path
        required: true
        schema:
          type: string
      responses:
        '404':
          description: Customer Not Found
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                company:
                  type: string
                firstname:
                  type: string
                group_ids:
                  type: array
                  items:
                    type: string
                lastname:
                  type: string
                mail:
                  type: string
                permissions:
                  type: object
                  properties:
                    defects:
                      type: boolean
                project_ids:
                  type: array
                  items:
                    type: string
                role_ids:
                  type: array
                  items:
                    type: string
                selected_is_mobile_syncs:
                  type: array
                  items:
                    type: string
                subcontractor:
                  type: boolean
                watcher:
                  type: boolean
      operationId: postApi:customerIdInvitations
      x-operation-id-source: derived
components:
  securitySchemes:
    apiKey:
      type: apiKey
      name: X-PlanRadar-API-Key
      in: header
externalDocs:
  description: Find out more about our development portal
  url: https://www.planradar.com/knowledge-base-overview/
