openapi: 3.2.0
info:
  title: PlanRadar's API Documentation Plans V2 API
  version: '2.0'
  description: Welcome to PlanRadar's API documentation, here you can find all the details about our APIs as well as test them online.
servers:
- url: /
tags:
- name: Plans V2
  description: Load/Manage plans
paths:
  /api/v2/{customer_id}/projects/{project_id}/components/{component_id}/plans/{id}:
    get:
      summary: Returns specific plan of a component
      tags:
      - Plans V2
      security:
      - apiKey: []
      description: This API returns a specific plan of a component based on its id.
      parameters:
      - name: customer_id
        in: path
        required: true
        schema:
          type: string
      - name: project_id
        in: path
        required: true
        schema:
          type: string
      - name: component_id
        in: path
        required: true
        schema:
          type: string
      - name: id
        in: path
        description: id of the plan
        required: true
        schema:
          type: string
      responses:
        '404':
          description: Plan Not Found
      operationId: getApiV2ByCustomerIdProjectsByProjectIdComponentsByComponentIdPlansById
      x-operation-id-source: derived
    put:
      summary: Update specific plan of a component
      tags:
      - Plans V2
      security:
      - apiKey: []
      description: This API update a specific plan of a component based on its id.
      x-websocket-response:
        channel: customer_{customerId}
        message_type: defectradar-components
        payload:
          type: object
          properties:
            plan-status:
              type: string
              description: Plan processing status
            customer-id:
              type: integer
            project-id:
              type: integer
      parameters:
      - name: customer_id
        in: path
        required: true
        schema:
          type: string
      - name: project_id
        in: path
        required: true
        schema:
          type: string
      - name: component_id
        in: path
        required: true
        schema:
          type: string
      - name: id
        in: path
        description: id of the plan
        required: true
        schema:
          type: string
      responses:
        '404':
          description: Plan Not Found
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                data:
                  type: object
                  properties:
                    attributes:
                      type: object
                      properties:
                        plan_scale:
                          type: object
                          example:
                            calibrate_scale:
                              point_1:
                                x: 0.3
                                y: 0.6
                              point_2:
                                x: 0.2
                                y: 0.4
                              distance: 4
                              unit: cm
                              width_px: 0.6
                              height_px: 1.2
                            calibrate_north:
                              south:
                                x: 0.2
                                y: 0.4
                              north:
                                x: 0.2
                                y: 0.4
      operationId: putApiV2ByCustomerIdProjectsByProjectIdComponentsByComponentIdPlansById
      x-operation-id-source: derived
  /api/v2/{customer_id}/projects/{project_id}/components/{component_id}/plans:
    get:
      summary: Returns all plans of a component
      tags:
      - Plans V2
      security:
      - apiKey: []
      description: This API returns all plans of a component based on the component's id.
      parameters:
      - name: customer_id
        in: path
        required: true
        schema:
          type: string
      - name: project_id
        in: path
        required: true
        schema:
          type: string
      - name: component_id
        in: path
        required: true
        schema:
          type: string
      - name: is_simple
        in: query
        description: send is_simple with true for retrieving simple plan versions data
        schema:
          type: boolean
      responses:
        '404':
          description: Plans Not Found
      operationId: getApiV2ByCustomerIdProjectsByProjectIdComponentsByComponentIdPlans
      x-operation-id-source: derived
  /api/v2/{customer_id}/projects/{project_id}/components/{component_id}/plans/{id}/skip_approval_request:
    put:
      summary: Skip approval request for this plan
      tags:
      - Plans V2
      security:
      - apiKey: []
      description: This api will remove the plan from an approval request if it belong to one and delete the approval request if it the last one included
      x-websocket-response:
        channel: customer_{customerId}
        message_type: defectradar-components
        payload:
          type: object
          properties:
            plan-status:
              type: string
              description: Plan processing status
            customer-id:
              type: integer
            project-id:
              type: integer
      parameters:
      - name: customer_id
        in: path
        required: true
        schema:
          type: string
      - name: project_id
        in: path
        required: true
        schema:
          type: string
      - name: component_id
        in: path
        required: true
        schema:
          type: string
      - name: id
        in: path
        description: Plan ID
        required: true
        schema:
          type: string
      responses:
        '404':
          description: Plan Not Found
      operationId: putApiV2ByCustomerIdProjectsByProjectIdComponentsByComponentIdPlansByIdSkipApprovalRequest
      x-operation-id-source: derived
components:
  securitySchemes:
    apiKey:
      type: apiKey
      name: X-PlanRadar-API-Key
      in: header
externalDocs:
  description: Find out more about our development portal
  url: https://www.planradar.com/knowledge-base-overview/
