openapi: 3.2.0
info:
  title: PlanRadar's API Documentation Invitation V1 API
  version: '2.0'
  description: Welcome to PlanRadar's API documentation, here you can find all the details about our APIs as well as test them online.
servers:
- url: /
tags:
- name: Invitation V1
paths:
  /api/v1/{customer_id}/invitations/{user_id}:
    get:
      summary: resend invitation
      tags:
      - Invitation V1
      description: resend an invitation for user has been invited before
      parameters:
      - name: customer_id
        in: path
        required: true
        schema:
          type: string
      - name: user_id
        in: path
        required: true
        schema:
          type: string
      responses:
        '404':
          description: Data not found
      operationId: getApiV1ByCustomerIdInvitationsByUserId
      x-operation-id-source: derived
    delete:
      summary: delete invitation
      tags:
      - Invitation V1
      description: delete a invitation
      parameters:
      - name: customer_id
        in: path
        required: true
        schema:
          type: string
      - name: user_id
        in: path
        required: true
        schema:
          type: string
      responses:
        '404':
          description: Data not found
      operationId: deleteApiV1ByCustomerIdInvitationsByUserId
      x-operation-id-source: derived
  /api/v1/{customer_id}/invitations:
    post:
      summary: Invite user
      tags:
      - Invitation V1
      security:
      - apiKey: []
      description: invite user
      parameters:
      - name: customer_id
        in: path
        required: true
        schema:
          type: string
      - name: user_id
        in: path
        required: true
        schema:
          type: string
      responses:
        '404':
          description: Data not found
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                data:
                  type: object
                  properties:
                    attributes:
                      type: object
                      properties:
                        active:
                          type: boolean
                        company:
                          type: string
                        firstname:
                          type: string
                        group_ids:
                          type: array
                          items: []
                        is_mobile_syncs:
                          type: array
                          items: []
                        lastname:
                          type: string
                        mail:
                          type: string
                        password:
                          type: string
                        permissions:
                          type: object
                          properties:
                            defects:
                              type: boolean
                        project_ids:
                          type: array
                          items: []
                        retype_password:
                          type: string
                        role_ids:
                          type: array
                          items: []
                        subcontractor:
                          type: boolean
                        time_zone_name:
                          type: string
                        watcher:
                          type: boolean
      operationId: postApiV1ByCustomerIdInvitations
      x-operation-id-source: derived
components:
  securitySchemes:
    apiKey:
      type: apiKey
      name: X-PlanRadar-API-Key
      in: header
externalDocs:
  description: Find out more about our development portal
  url: https://www.planradar.com/knowledge-base-overview/
