openapi: 3.2.0
info:
  title: PlanRadar's API Documentation Components V2 API
  version: '2.0'
  description: Welcome to PlanRadar's API documentation, here you can find all the details about our APIs as well as test them online.
servers:
- url: /
tags:
- name: Components V2
  description: Create PlanRadar Components/Plans
paths:
  /api/v2/{customer_id}/projects/{project_id}/components/project_components:
    get:
      summary: Returns all components of a project based on its id
      tags:
      - Components V2
      description: This API returns all components of a project.
      security:
      - apiKey: []
      parameters:
      - name: customer_id
        in: path
        required: true
        schema:
          type: string
      - name: project_id
        in: path
        required: true
        schema:
          type: string
      - name: last_sync_date
        in: query
        description: ' is a Unix Timestamp. If it is set, only components that were created after that timestamp will be returned'
        schema:
          type: string
      responses:
        '404':
          description: Components Not Found
      operationId: getApiV2ByCustomerIdProjectsByProjectIdComponentsProjectComponents
      x-operation-id-source: derived
  /api/v2/{customer_id}/projects/{project_id}/components/{id}:
    get:
      summary: Returns specific project component
      tags:
      - Components V2
      description: This API returns a specific project component based on its id.
      security:
      - apiKey: []
      parameters:
      - name: customer_id
        in: path
        required: true
        schema:
          type: string
      - name: project_id
        in: path
        required: true
        schema:
          type: string
      - name: id
        in: path
        description: ' id of the component'
        required: true
        schema:
          type: string
      responses:
        '404':
          description: Component Not Found
      operationId: getApiV2ByCustomerIdProjectsByProjectIdComponentsById
      x-operation-id-source: derived
components:
  securitySchemes:
    apiKey:
      type: apiKey
      name: X-PlanRadar-API-Key
      in: header
externalDocs:
  description: Find out more about our development portal
  url: https://www.planradar.com/knowledge-base-overview/
