openapi: 3.2.0
info:
  title: PlanRadar's API Documentation Ticket Imports API
  version: '2.0'
  description: Welcome to PlanRadar's API documentation, here you can find all the details about our APIs as well as test them online.
servers:
- url: /
tags:
- name: Ticket Imports
paths:
  /api/v1/{customer_id}/projects/{project_id}/ticket_imports:
    post:
      summary: Upload file with read content
      tags:
      - Ticket Imports
      parameters:
      - name: customer_id
        in: path
        required: true
        schema:
          type: string
      - name: project_id
        in: path
        required: true
        schema:
          type: string
      responses:
        '404':
          description: Plan Not Found
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                data[][attributes][file]:
                  type: string
                  format: binary
                data[][attributes][options]:
                  type: object
                  description: '{"first_line_is_headers":true,"validate_tickets":true,"seperated_by":"comma"}'
                data[][attributes][ticket_type_id]:
                  type: string
                data[][attributes][uuid]:
                  type: string
                  description: UUID of the ticket import record if you want to update existing record
                data[][attributes][file_name]:
                  type: string
                  description: Name of the file being uploaded
      operationId: postApiV1ByCustomerIdProjectsByProjectIdTicketImports
      x-operation-id-source: derived
components:
  securitySchemes:
    apiKey:
      type: apiKey
      name: X-PlanRadar-API-Key
      in: header
externalDocs:
  description: Find out more about our development portal
  url: https://www.planradar.com/knowledge-base-overview/
